local addonName, addon = ...

-- SoundKit IDs use PlaySound; fileDataIDs use PlaySoundFile.
addon.SOUND_LIST = {
    { label = "Ready Check", soundKitID = 8960 },
    { label = "Auction Window", soundKitID = 5274 },
    { label = "Gold Coins", soundKitID = 120 },
    { label = "Quest Complete", soundKitID = 618 },
    { label = "Player Invite", soundKitID = 880 },
    { label = "Alarm Clock", soundKitID = 12889 },
    { label = "Garrison Toast", soundKitID = 44295 },
    { label = "Whisper", soundKitID = 3086 },
    { label = "Loot Epic", soundKitID = 31578 },
    { label = "Bell Toll", soundKitID = 23404 },
    { label = "Option Click", soundKitID = 852 },
    { label = "Checkbox On", soundKitID = 856 },
    { label = "Checkbox Off", soundKitID = 857 },
    { label = "Main Menu Open", soundKitID = 850 },
    { label = "Main Menu Close", soundKitID = 851 },
    { label = "Window Close", soundKitID = 799 },
    { label = "Character Tab", soundKitID = 841 },
    { label = "Chat Scroll", soundKitID = 1115 },
    { label = "Backpack Open", soundKitID = 862 },
    { label = "Backpack Close", soundKitID = 863 },
    { label = "Raid Warning", soundKitID = 8959 },
    { label = "Level Up", soundKitID = 888 },
    { label = "PVP Flag", soundKitID = 8174 },
    { label = "Gong", soundKitID = 11742 },
    { label = "Horn", soundKitID = 34090 },
    { label = "Chicken", fileDataID = 546072 },
    { label = "Murloc", fileDataID = 556000 },
    { label = "Bear", fileDataID = 1256853 },
    { label = "Cat Meow", fileDataID = 599720 },
    { label = "Crash", fileDataID = 1716534 },
}
